name: Bemilk
main: xiaokai.bemilk.Bemilk
api:
- 1.0.0
version: 1.0.0.alpha
load: POSTWORLD
website: http://EpicFX.cn
author: Winfxk
loadbefore:
- EconomyAPI
commands:
   shop:
      description: §9商店主命令
      permission: Bemilk.Command.main
      usage: §b/§6shop §chelp
      aliases:
      - 商店
      - bemilk
permissions:
   Bemilk.Command.main:
      description: 商店主命令
      default: true