name: Bemilk
main: xiaokai.bemilk.Bemilk
api:
- 1.0.0
version: 1.2.1
load: POSTWORLD
website: http://EpicFX.cn
author: Winfxk
depend:
- EconomyAPI
permissions:
   Bemilk.Command.Shop:
      description: 商店命令
      default: true
   Bemilk.Command.Admin:
      description: 管理命令
      default: true