name: Bemilk
main: cn.winfxk.nukkit.bemilk.Bemilk
api:
  - 1.0.0
version: 2.0
load: POSTWORLD
depend:
  - WinfxkLib
loadbefore:
  - WinfxkLib
website: http://Winfxk.cn
author: Winfxk
permissions:
  Bemilk.Command.Shop:
    description: 商店命令
    default: true
  Bemilk.Command.Admin:
    description: 管理命令
    default: true
