#配置开始==================
#每个玩家进服的时候都会给一个，当拿着这个玩意右键的时候打开商店菜单主页，特殊值可以不限定，当特殊值为x时默认匹配所有，特殊值默认为0,当这个值为空(null{在Yml文件内用~表示})时不适用快捷工具！
快捷工具: '345:0'
#当这个值为真时，撤销使用快捷工具打开的事件
打开撤销: true
货币单位: 金币
检测更新: true
检测更新间隔: 21600
#假如玩家在这个时间段内双击，将无法用快捷工具多次打开主页，防止刷屏
屏蔽玩家双击间隔: 500
定时检查快捷工具间隔: 60
是否允许玩家丢弃快捷工具: false
管理员: []
管理员白名单: false
折叠选项: true
隐藏无权商店: false
隐藏金钱数不匹配的商店: false
定时保存间隔: 30
物品修复项目图标: textures/gui/newgui/anvil-hammer.png
物品附魔项目图标: textures/items/textures/ui/haste_effect.png
搜索按钮图标: textures/gui/newgui/magnifyingGlass.png
个人商店创建按钮图标: textures/gui/newgui/Friends.png
命令商店按钮图标: textures/blocks/bed_feet_side.png
限制OP使用个人商店: false
限制创造模式使用个人商店: true
玩家重生时重置玩家缓存数据: false
限制创造模式使用商店: true
重生进服等事件检测玩家快捷工具持有: true
数据刷新间隔: 600
近似ID: true
显示错误按钮: false
默认货币类型: EconomyAPI
命令商店显示内容: §6命令商店§f|§5{Money}§f|§8{Permission}